#!/bin/bash

# Dependency Check
function check {
    show_info "Checking dependencies..."
    PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' whiptail|grep "install ok installed")
    if [ "" == "$PKGCHECK" ]; then
        echo
        show_info "This script makes use of 'whiptail' and it is not present on your system.\n"
        show_question 'Would you like to install it to continue? (Y)es, (N)o: ' && read REPLY
        echo ''
        case $REPLY in
        # Positive action
        [Yy]* )
            show_warning 'Requires root privileges'
            sudo aptitude install whiptail
            show_success 'Whiptail installed.\n'
            main
            ;;
        # Negative action
        [Nn]* )
            show_info "Exiting.\n"
            exit 99
            ;;
        # Error
        * )
            show_error '\aPlease answer Y or N.\n' && check
            ;;
        esac
    else
        sleep 1
        show_info "all set.\n\n"
    fi
}
