#!/bin/bash

dir="$(dirname "$0")"

FAVS="$dir/data/favorites.list"

# Install Favorite Applications
function favorites {
    if (eval `resize` && whiptail \
        --title "Favorite Applications" \
        --yesno "Current list of favorite applications to install: \n\n$(cat $FAVS) \n\nProceed with installation?" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        --scrolltext ) then
        show_info '\nInstalling favorite applications...\n'
        show_warning '(requires root privileges)\n'
        # Feel free to change the contents of 'favorites.list' in the data folder to whatever suits your preference.
        sudo aptitude install $(< $FAVS)
        # Done
        show_success 'Favorites installed.\n'
        whiptail --title "Finished" --msgbox "Installation of favorites complete." 8 78
    fi
}
