#!/bin/bash

# Perform system upgrade
function update {
if (whiptail --title "System Update" --yesno "Proceed with system update?" 10 60) then
    # Update repository information
    show_info '\nUpdating repository information...\n'
    show_warning '(requires root privileges)\n'
    sudo aptitude update
    # Dist-Upgrade
    show_info 'Performing system upgrade...\n'
    sudo aptitude dist-upgrade
    # Done
    show_success 'System upgraded.\n'
    whiptail --title "Finished" --msgbox "System update complete." 8 78
fi
}
