#!/bin/bash

dir="$(dirname "$0")"

UTILS="$dir/data/utilities.list"

# Install Favourite System Utilities
function utilities {
    if (eval `resize` && whiptail --title \
        "System Utilities"  --yesno \
        "Current list of system utilities: \n\n$(cat $UTILS) \n\nProceed with installation?" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        --scrolltext ) then
        show_info '\nInstalling...\n'
        show_warning '(requires root privileges)\n'
        # Feel free to change the contents of 'utilities.list' in the data folder to whatever suits your preference.
        sudo aptitude install $(< $UTILS)
        # Done
        show_success 'Utilities installed.\n'
        whiptail --title "Finished" --msgbox "Installation complete." 8 78
    fi
}
